# Generated by Django 2.0.5 on 2018-09-03 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180903_2006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseResourse',
            new_name='CourseResource',
        ),
    ]
