# Generated by Django 2.1 on 2018-08-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180817_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('regiester', '注册'), ('forget', '找回密码')], max_length=10, verbose_name='发送类型'),
        ),
    ]
